package lab_1;

// version 1.0
// <editor-fold defaultstate="collapsed" desc="do not edit this file">
import java.util.*;

public class Test {
    private static int score;
    private static int total;

    protected static void begin() {
        score = 0;
        total = 0;
    }

    protected static void check(int expected, int actual) {
        total++;
        if (expected == actual) {
            score++;
        }
    }

    protected static void check(char expected, char actual) {
        total++;
        if (expected == actual) {
            score++;
        }
    }

    protected static void check(int[] expected, int[] actual) {
        total++;
        if (Arrays.equals(expected, actual)) {
            score++;
        }
    }

    protected static void check(boolean expected, boolean actual) {
        total++;
        if (expected == actual) {
            score++;
        }
    }

    protected static void check(String expected, String actual) {
        total++;
        if (expected.equals(actual)) {
            score++;
        }
    }

    protected static void checkClose(double expected, double actual) {
        total++;
        if (Math.abs(expected - actual) < 0.00001) {
            score++;
        }
    }

    protected static void getScore() {
        System.out.printf("You score %.2f%%.%n", 100.0 * score / total);
    }
}
// </editor-fold>
