/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Phon.java
 *
 * Created on Jun 28, 2010, 12:35:23 PM
 */

package phon;

/**
 *
 * @author CS-KU
 */
public class Phon extends javax.swing.JFrame {
    private String number="" ;
    /** Creates new form Phon */
    public Phon() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        buttonNumber1 = new java.awt.Button();
        buttonNumber2 = new java.awt.Button();
        buttonNumber3 = new java.awt.Button();
        buttonNumber4 = new java.awt.Button();
        buttonNumber5 = new java.awt.Button();
        buttonNumber6 = new java.awt.Button();
        buttonNumber7 = new java.awt.Button();
        buttonNumber8 = new java.awt.Button();
        buttonNumber9 = new java.awt.Button();
        buttonNumber11 = new java.awt.Button();
        buttonNumber0 = new java.awt.Button();
        buttonNumber12 = new java.awt.Button();
        outLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(new java.awt.GridLayout(4, 0));

        buttonNumber1.setLabel("1");
        buttonNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber1ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber1);

        buttonNumber2.setLabel("2");
        buttonNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber2ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber2);

        buttonNumber3.setLabel("3");
        buttonNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber3ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber3);

        buttonNumber4.setLabel("4");
        buttonNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber4ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber4);

        buttonNumber5.setLabel("5");
        buttonNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber5ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber5);

        buttonNumber6.setLabel("6");
        buttonNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber6ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber6);

        buttonNumber7.setLabel("7");
        buttonNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber7ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber7);

        buttonNumber8.setLabel("8");
        buttonNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber8ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber8);

        buttonNumber9.setLabel("9");
        buttonNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber9ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber9);

        buttonNumber11.setLabel("*");
        buttonNumber11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber11ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber11);

        buttonNumber0.setLabel("0");
        buttonNumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber0ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber0);

        buttonNumber12.setLabel("#");
        buttonNumber12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber12ActionPerformed(evt);
            }
        });
        panel1.add(buttonNumber12);

        outLabel.setBackground(new java.awt.Color(255, 255, 255));
        outLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        outLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(outLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private void appendNumber(String s)
   {
       if(number.length()<12){
          number+= s;
          outLabel.setText(number);
          if(number.length()==2||number.length()==7) number+="-";
       }
   }
    private void buttonNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber1ActionPerformed
      appendNumber("1");
    }//GEN-LAST:event_buttonNumber1ActionPerformed

    private void buttonNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber2ActionPerformed
       appendNumber("2");
    }//GEN-LAST:event_buttonNumber2ActionPerformed

    private void buttonNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber3ActionPerformed
        appendNumber("3");
    }//GEN-LAST:event_buttonNumber3ActionPerformed

    private void buttonNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber4ActionPerformed
        appendNumber("4");
    }//GEN-LAST:event_buttonNumber4ActionPerformed

    private void buttonNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber5ActionPerformed
        appendNumber("5");
    }//GEN-LAST:event_buttonNumber5ActionPerformed

    private void buttonNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber6ActionPerformed
        appendNumber("6");
    }//GEN-LAST:event_buttonNumber6ActionPerformed

    private void buttonNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber7ActionPerformed
        appendNumber("7");
    }//GEN-LAST:event_buttonNumber7ActionPerformed

    private void buttonNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber8ActionPerformed
        appendNumber("8");
    }//GEN-LAST:event_buttonNumber8ActionPerformed

    private void buttonNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber9ActionPerformed
       appendNumber("9");
    }//GEN-LAST:event_buttonNumber9ActionPerformed

    private void buttonNumber11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber11ActionPerformed
       appendNumber("*");
    }//GEN-LAST:event_buttonNumber11ActionPerformed

    private void buttonNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber0ActionPerformed
        appendNumber("0");
    }//GEN-LAST:event_buttonNumber0ActionPerformed

    private void buttonNumber12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber12ActionPerformed
        appendNumber("#");
    }//GEN-LAST:event_buttonNumber12ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonNumber0;
    private java.awt.Button buttonNumber1;
    private java.awt.Button buttonNumber11;
    private java.awt.Button buttonNumber12;
    private java.awt.Button buttonNumber2;
    private java.awt.Button buttonNumber3;
    private java.awt.Button buttonNumber4;
    private java.awt.Button buttonNumber5;
    private java.awt.Button buttonNumber6;
    private java.awt.Button buttonNumber7;
    private java.awt.Button buttonNumber8;
    private java.awt.Button buttonNumber9;
    private javax.swing.JLabel outLabel;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

}
