/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainManu.java
 *
 * Created on 9 ต.ค. 2553, 21:56:55
 */

package thelastproject;

import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class MainManu extends javax.swing.JFrame {
    /** Creates new form MainManu */
    int i,time;
    private fixRoom fix;
    private Member mem;
    private Calendar upDateTime = Calendar.getInstance();
    public MainManu() {
        initComponents();
        this.time = upDateTime.get(Calendar.HOUR);
        for(i=101;i<=312;i++){
            if(i>=101&&i<=112||i>=201&&i<=212||i>=301&&i<=312){
            try {
            if(fixRoom.selectByRoom(i).geth8().equals("X")==false&& time == 8 && mem.getTime() != 8.0) {
                mem = Member.selectByID(fix.geth8());
                mem.setTimeUse(8.0);
                mem.timeUse();
                mem.setRoomU(i);
                mem.roomUse();
            }
            else if(fixRoom.selectByRoom(i).geth9().equals("X")==false&& time == 9 && mem.getTime() != 9.0) {
                mem = Member.selectByID(fix.geth9());
                mem.setTimeUse(9.0);
                mem.timeUse();
                mem.setRoomU(i);
                mem.roomUse();
            }
            else if(fixRoom.selectByRoom(i).geth10().equals("X")==false&& time == 10 && mem.getTime() != 10.0) {
                mem = Member.selectByID(fix.geth10());
                mem.setTimeUse(10.0);
                mem.timeUse();
                mem.setRoomU(i);
                mem.roomUse();
            }
            else if(fixRoom.selectByRoom(i).geth11().equals("X")==false&& time == 11 && mem.getTime() != 11.0) {
                mem = Member.selectByID(fix.geth11());
                mem.setTimeUse(11.0);
                mem.timeUse();
                mem.setRoomU(i);
                mem.roomUse();
            }
            else if(fixRoom.selectByRoom(i).geth12().equals("X")==false&& time == 12 && mem.getTime() != 12.0) {
                mem = Member.selectByID(fix.geth12());
                mem.setTimeUse(12.0);
                mem.timeUse();
                mem.setRoomU(i);
                mem.roomUse();
            }
            else if(fixRoom.selectByRoom(i).geth13().equals("X")==false&& time == 13 && mem.getTime() != 13.0) {
                mem = Member.selectByID(fix.geth13());
                mem.setTimeUse(13.0);
                mem.timeUse();
                mem.setRoomU(i);
                mem.roomUse();
            }
            else if(fixRoom.selectByRoom(i).geth14().equals("X")==false&& time == 14 && mem.getTime() != 14.0) {
                mem = Member.selectByID(fix.geth14());
                mem.setTimeUse(14.0);
                mem.timeUse();
                mem.setRoomU(i);
                mem.roomUse();
            }
            else if(fixRoom.selectByRoom(i).geth15().equals("X")==false&& time == 15 && mem.getTime() != 15.0) {
                mem = Member.selectByID(fix.geth15());
                mem.setTimeUse(15.0);
                mem.timeUse();
                mem.setRoomU(i);
                mem.roomUse();
            }
            else if(fixRoom.selectByRoom(i).geth16().equals("X")==false&& time == 16 && mem.getTime() != 16.0) {
                mem = Member.selectByID(fix.geth16());
                mem.setTimeUse(16.0);
                mem.timeUse();
                mem.setRoomU(i);
                mem.roomUse();
            }
            } catch (Exception ex) {
                Logger.getLogger(SearchRoom.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(i==113||i==213) i+=87;
        }
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        inputPass = new javax.swing.JPasswordField();
        Exit = new javax.swing.JButton();
        login = new javax.swing.JButton();
        rePass = new javax.swing.JButton();
        sendPass = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id.setFont(new java.awt.Font("Tahoma", 1, 11));
        id.setText("ID");

        inputID.setFont(new java.awt.Font("Tahoma", 1, 11));

        pass.setFont(new java.awt.Font("Tahoma", 1, 11));
        pass.setText("Password");

        register.setFont(new java.awt.Font("Tahoma", 1, 11));
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        inputPass.setFont(new java.awt.Font("Tahoma", 1, 11));
        inputPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPassActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Tahoma", 1, 11));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        login.setFont(new java.awt.Font("Tahoma", 1, 11));
        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        rePass.setFont(new java.awt.Font("Tahoma", 1, 11));
        rePass.setText("เปลี่ยนPassword");
        rePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rePassActionPerformed(evt);
            }
        });

        sendPass.setFont(new java.awt.Font("Tahoma", 1, 11));
        sendPass.setText("ลืมPassword");
        sendPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendPassActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("ผู้พัฒนา");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rePass, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(sendPass, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputID, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(inputPass, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rePass)
                            .addComponent(sendPass))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(register)
                            .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new RegisterID().setVisible(false);
    }//GEN-LAST:event_registerActionPerformed

    private void inputPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPassActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       try {
            // TODO add your handling code here:
            Member m = Member.selectByID(inputID.getText());
            if( m.getId().equals(inputID.getText())&&m.getPass().equals(inputPass.getText())){
              this.dispose();
              ClassRoomSection1 c = new ClassRoomSection1(m.getId(),m.getAdmin());
              c.setVisible(true);
            }
           else if((m.getPass().equals(inputPass.getText())) == false)
           {
               JOptionPane.showMessageDialog(this,"Password ผิด");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"ไม่มี ID อยู่ในระบบ!");
            Logger.getLogger(RegisterID.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void rePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rePassActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new RePass().setVisible(true);
    }//GEN-LAST:event_rePassActionPerformed

    private void sendPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendPassActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new SendPass().setVisible(true);
    }//GEN-LAST:event_sendPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Credit().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainManu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel id;
    private javax.swing.JTextField inputID;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton login;
    private javax.swing.JLabel pass;
    private javax.swing.JButton rePass;
    private javax.swing.JButton register;
    private javax.swing.JButton sendPass;
    // End of variables declaration//GEN-END:variables

}
