/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchRoom.java
 *
 * Created on 9 ต.ค. 2553, 21:49:44
 */

package thelastproject;

import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class SearchRoom extends javax.swing.JFrame {
    String ID;
    int a;
    private Calendar upDateTime = Calendar.getInstance();
    /** Creates new form SearchRoom */
    public SearchRoom(String id, int a) {
        initComponents();
        this.ID=id;
        this.a=a;
        if(a==0) admin.setVisible(false);
        else admin.setVisible(true);
        upDateTime.get(Calendar.HOUR);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        getNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        getSec = new javax.swing.JComboBox();
        search = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        selecRoom = new javax.swing.JButton();
        back = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        timeS = new javax.swing.JComboBox();
        roomList = new java.awt.List();
        admin1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("เวลาที่ต้องการใช้งาน");

        getNum.setText("0");
        getNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNumActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("จำนวนการรองรับคน");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Sectionที่ต้องการ");

        getSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ทั้งหมด", "Section 1", "Section 2", "Section 3" }));

        search.setFont(new java.awt.Font("Tahoma", 1, 11));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 11));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        selecRoom.setFont(new java.awt.Font("Tahoma", 1, 11));
        selecRoom.setText("เลือกห้อง");
        selecRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecRoomActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 1, 11));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        admin.setFont(new java.awt.Font("Tahoma", 1, 11));
        admin.setText("Admin Room");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        timeS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8.00", "9.00", "10.00", "11.00", "12.00", "13.00", "14.00", "15.00", "16.00" }));

        admin1.setFont(new java.awt.Font("Tahoma", 1, 11));
        admin1.setText("User Room");
        admin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(roomList, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(getSec, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(timeS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(getNum))
                            .addComponent(admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(selecRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomList, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(timeS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(search)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout)
                    .addComponent(back)
                    .addComponent(selecRoom)
                    .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new ClassRoomSection1(ID,a).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(SearchRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backActionPerformed

    private void selecRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecRoomActionPerformed
        // TODO add your handling code here:
        try {
        int x = Integer.parseInt(roomList.getSelectedItem().substring(0, 3));
        if(x>=101&&x<=112||x>=201&&x<=212||x>=301&&x<=312){
        this.dispose();
        Room r = new Room(ID,x,a);
        r.setVisible(true);
        }
        } catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, "กรุณาเลือกห้อง");    
        }
       // JOptionPane.showMessageDialog(this, "กรุณาเลือกห้อง");
    }//GEN-LAST:event_selecRoomActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainManu().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminRoom(ID,a).setVisible(true);
}//GEN-LAST:event_adminActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        int n = timeS.getSelectedIndex();
                int sec = getSec.getSelectedIndex();
        int i,m = 0,p=101,num =500;
        try{
        num = Integer.parseInt(getNum.getText());
        roomList.removeAll();
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "กรุณาใส่เฉพาะตัวเลขในช่องจำนวนคนเท่านั้น");
        }

        if(sec==0){
            p=101;
            m=312;
        }
        if(sec==1){
            p=101;
            m=112;
        }
        if(sec==2){
            p=201;
            m=212;
        }if(sec==3){
            p=301;
            m=312;
        }
        for(i=p;i<=m;i++){
            if(i>=101&&i<=112||i>=201&&i<=212||i>=301&&i<=312){
            try {
                fixRoom r = fixRoom.selectByRoom(i);
                if(n == 0 && r.geth8().equals("X") && r.getNum()>=num && r.getNum()<=(num+50)) {
                    roomList.add(i+"  Capacity  "+r.getNum());
                }
                else if(n == 1 && r.geth9().equals("X") && r.getNum()>=num && r.getNum()<=(num+50)){
                    roomList.add(i+"  Capacity  "+r.getNum());
                }
                else if(n == 2 && r.geth10().equals("X") && r.getNum()>=num && r.getNum()<=(num+50)){
                    roomList.add(i+"  Capacity  "+r.getNum());
                }
                else if(n == 3 && r.geth11().equals("X") && r.getNum()>=num && r.getNum()<=(num+50)){
                    roomList.add(i+"  Capacity  "+r.getNum());
                }
                else if(n == 4 && r.geth12().equals("X") && r.getNum()>=num && r.getNum()<=(num+50)){
                    roomList.add(i+"  Capacity  "+r.getNum());
                }
                else if(n == 5 && r.geth13().equals("X") && r.getNum()>=num && r.getNum()<=(num+50)){
                    roomList.add(i+"  Capacity  "+r.getNum());
                }
                else if(n == 6 && r.geth14().equals("X") && r.getNum()>=num && r.getNum()<=(num+50)){
                    roomList.add(i+"  Capacity  "+r.getNum());
                }
                else if(n == 7 && r.geth15().equals("X") && r.getNum()>=num && r.getNum()<=(num+50)){
                    roomList.add(i+"  Capacity  "+r.getNum());
                }
                else if(n == 8 && r.geth16().equals("X") && r.getNum()>=num && r.getNum()<=(num+50)){
                    roomList.add(i+"  Capacity  "+r.getNum());
                }
            } catch (Exception ex) {
                Logger.getLogger(SearchRoom.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(i==113||i==213) i+=87;
        }
    }//GEN-LAST:event_searchActionPerformed

    private void getNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getNumActionPerformed

    private void admin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UserRoom(ID, a).setVisible(true);
}//GEN-LAST:event_admin1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton admin1;
    private javax.swing.JButton back;
    private javax.swing.JTextField getNum;
    private javax.swing.JComboBox getSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logout;
    private java.awt.List roomList;
    private javax.swing.JButton search;
    private javax.swing.JButton selecRoom;
    private javax.swing.JComboBox timeS;
    // End of variables declaration//GEN-END:variables

}
