/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserRoom.java
 *
 * Created on 16 ต.ค. 2553, 12:57:30
 */

package thelastproject;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author BOND
 */
public class UserRoom extends javax.swing.JFrame {
    String ID,s="";
    int a;
    private fixRoom r = new fixRoom ();
    private Member m = new Member ();
    /** Creates new form UserRoom */
    public UserRoom(String id, int a) {
        try {
            initComponents();
            this.ID = id;
            this.a = a;
            if (r.selectBy8H(ID).geth8().equals(ID)) {
                if (m.selectByID(ID).getTime() == 8.0) {
                    s = "Not Conferm";
                } else {
                    s = "Conferm";
                }
                list.add(r.selectBy8H(ID).getNoRoom() + "" + s +" 8.00 ");
            }
            if (r.selectBy9H(ID).geth9().equals(ID)) {
                if (m.selectByID(ID).getTime() == 9.0) {
                    s = "Not Conferm";
                } else {
                    s = "Conferm";
                }
                list.add(r.selectBy9H(ID).getNoRoom() + "" + s+" 9.00 ");
            }
            if (r.selectBy10H(ID).geth10().equals(ID)) {
                if (m.selectByID(ID).getTime() == 10.0) {
                    s = "Not Conferm";
                } else {
                    s = "Conferm";
                }
                list.add(r.selectBy10H(ID).getNoRoom() + "" + s+" 10.00 ");
            }
            if (r.selectBy11H(ID).geth11().equals(ID)) {
                if (m.selectByID(ID).getTime() == 11.0) {
                    s = "Not Conferm";
                } else {
                    s = "Conferm";
                }
                list.add(r.selectBy11H(ID).getNoRoom() + "" + s+" 11.00 ");
            }
            if (r.selectBy12H(ID).geth12().equals(ID)) {
                if (m.selectByID(ID).getTime() == 12.0) {
                    s = "Not Conferm";
                } else {
                    s = "Conferm";
                }
                list.add(r.selectBy12H(ID).getNoRoom() + "" + s+" 12.00 ");
            }
            if (r.selectBy13H(ID).geth13().equals(ID)) {
                if (m.selectByID(ID).getTime() == 13.0) {
                    s = "Not Conferm";
                } else {
                    s = "Conferm";
                }
                list.add(r.selectBy13H(ID).getNoRoom() + "" + s+" 13.00 ");
            }
            if (r.selectBy14H(ID).geth14().equals(ID)) {
                if (m.selectByID(ID).getTime() == 14.0) {
                    s = "Not Conferm";
                } else {
                    s = "Conferm";
                }
                list.add(r.selectBy14H(ID).getNoRoom() + "" + s+" 14.00 ");
            }
            if (r.selectBy15H(ID).geth15().equals(ID)) {
                if (m.selectByID(ID).getTime() == 15.0) {
                    s = "Not Conferm";
                } else {
                    s = "Conferm";
                }
                list.add(r.selectBy15H(ID).getNoRoom() + "" + s+" 15.00 ");
            }
            if (r.selectBy16H(ID).geth16().equals(ID)) {
                if (m.selectByID(ID).getTime() == 16.0) {
                    s = "Not Conferm";
                } else {
                    s = "Conferm";
                }
                list.add(r.selectBy16H(ID).getNoRoom() + "" + s+" 16.00 ");
            }
        } catch (Exception ex) {
            Logger.getLogger(UserRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        list = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back.setFont(new java.awt.Font("Tahoma", 1, 11));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Tahoma", 1, 11));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("ชื่อ-นามสกุล");

        jLabel3.setText("รายชื่อห้องที่เคยจองใช้งาน");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addGap(173, 173, 173)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(Logout))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new ClassRoomSection1(ID, a).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(AdminRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_backActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainManu().setVisible(true);
}//GEN-LAST:event_LogoutActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.List list;
    // End of variables declaration//GEN-END:variables

}
