/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB_11;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author HeartLess
 */
public class RentDormitory extends javax.swing.JFrame {

    /**
     * Creates new form RentDormitory
     */
    int i;
    double dormitoryPrice = 0 ,electricityUnit = 0 ,waterUnit = 0 ,wiFiPrice = 0 ,total = 0;
    double[] electricityPrice = new double[4] ,waterPrice = new double[4];
    String more = "0" ,roomNumber = "" ;
    public RentDormitory() {
        initComponents();
        MoreField.setVisible(false);
        jButton2.setVisible(false);
        jLabel34.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        ElectricityPriceField3 = new javax.swing.JTextField();
        WaterUnitField3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        WaterPriceField2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        WaterPriceField3 = new javax.swing.JTextField();
        MoreField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ElectricityPriceField2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        RoomNumberField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        WaterUnitField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ElectricityPriceField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        WiFiPriceField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        WaterPriceField1 = new javax.swing.JTextField();
        DormitoryPriceField = new javax.swing.JTextField();
        WaterPriceField4 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ElectricityPriceField4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        ElectricityUnitField1 = new javax.swing.JTextField();
        ElectricityUnitField2 = new javax.swing.JTextField();
        ElectricityUnitField = new javax.swing.JTextField();
        ElectricityUnitField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        WaterUnitField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        WaterUnitField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TotalField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel17.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel17.setText("ค่าไฟหน่วยที่ 201 ขึ้นไป หน่วยละ 10 บาท จำนวน");

        ElectricityPriceField3.setEditable(false);
        ElectricityPriceField3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ElectricityPriceField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ElectricityPriceField3.setText("0");

        WaterUnitField3.setEditable(false);
        WaterUnitField3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WaterUnitField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        WaterUnitField3.setText("0");

        jLabel28.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel28.setText("หน่วย");

        jLabel29.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel29.setText("หน่วย");

        jLabel30.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel30.setText("หน่วย");

        jLabel31.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel31.setText("หน่วย");

        jLabel32.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel32.setText("หน่วย");

        jLabel33.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel33.setText("หน่วย");

        WaterPriceField2.setEditable(false);
        WaterPriceField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WaterPriceField2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        WaterPriceField2.setText("0");

        jLabel34.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel34.setText("more room? (9 for more OR others for end )");

        WaterPriceField3.setEditable(false);
        WaterPriceField3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WaterPriceField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        WaterPriceField3.setText("0");

        MoreField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MoreField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        MoreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreFieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel18.setText("ค่าน้ำหน่วยที่ 11 ขึ้นไป หน่วยละ 25 บาท จำนวน");

        jLabel35.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel35.setText("หมายเลขห้องพัก");

        jLabel19.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel19.setText("บาท");

        jLabel20.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel20.setText("บาท");

        jLabel21.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel21.setText("บาท");

        jLabel22.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel22.setText("บาท");

        ElectricityPriceField2.setEditable(false);
        ElectricityPriceField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ElectricityPriceField2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ElectricityPriceField2.setText("0");

        jLabel23.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel23.setText("ค่าไฟหน่วยที่ 51-200 หน่วยละ 9 บาท จำนวน");

        jLabel24.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel24.setText("ค่าน้ำรวม");

        RoomNumberField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RoomNumberField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel5.setText("หน่วยน้ำประปา");

        jLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel12.setText("บาท");

        WaterUnitField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WaterUnitField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        WaterUnitField.setText("0");

        jButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jButton1.setText("คิดเงิน");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel6.setText("หน่วย");

        jButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jButton2.setText("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ElectricityPriceField1.setEditable(false);
        ElectricityPriceField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ElectricityPriceField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ElectricityPriceField1.setText("0");

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel7.setText("ค่าไฟ 50 หน่วยแรก หน่วยละ 8 บาท จำนวน");

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel8.setText("บาท");

        WiFiPriceField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WiFiPriceField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        WiFiPriceField.setText("0");
        WiFiPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WiFiPriceFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel9.setText("ค่า Wifi");

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel1.setText("ค่าห้อง");

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel10.setText("บาท");

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel2.setText("บาท");

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel11.setText("ค่าน้ำ 5 หน่วยแรก หน่วยละ 15 บาท จำนวน");

        WaterPriceField1.setEditable(false);
        WaterPriceField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WaterPriceField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        WaterPriceField1.setText("0");

        DormitoryPriceField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DormitoryPriceField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        DormitoryPriceField.setText("0");

        WaterPriceField4.setEditable(false);
        WaterPriceField4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WaterPriceField4.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        WaterPriceField4.setText("0");

        jLabel25.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel25.setText("บาท");

        jLabel26.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel26.setText("ค่าไฟรวม");

        ElectricityPriceField4.setEditable(false);
        ElectricityPriceField4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ElectricityPriceField4.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ElectricityPriceField4.setText("0");

        jLabel27.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel27.setText("บาท");

        ElectricityUnitField1.setEditable(false);
        ElectricityUnitField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ElectricityUnitField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ElectricityUnitField1.setText("0");

        ElectricityUnitField2.setEditable(false);
        ElectricityUnitField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ElectricityUnitField2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ElectricityUnitField2.setText("0");

        ElectricityUnitField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ElectricityUnitField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ElectricityUnitField.setText("0");

        ElectricityUnitField3.setEditable(false);
        ElectricityUnitField3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ElectricityUnitField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ElectricityUnitField3.setText("0");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel3.setText("หน่วยไฟฟ้า");

        WaterUnitField1.setEditable(false);
        WaterUnitField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WaterUnitField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        WaterUnitField1.setText("0");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel4.setText("หน่วย");

        WaterUnitField2.setEditable(false);
        WaterUnitField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WaterUnitField2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        WaterUnitField2.setText("0");

        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel13.setText("บาท");

        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel14.setText("ค่าเช่าที่ต้องจ่าย");

        TotalField.setEditable(false);
        TotalField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        TotalField.setText("0");

        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel15.setText("ค่าเช่าหอ");

        jLabel16.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel16.setText("ค่าน้ำหน่วยที่ 6-10 หน่วยละ 20 บาท จำนวน");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel24)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel16)
                                                            .addComponent(jLabel18)
                                                            .addComponent(jLabel11))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(WaterUnitField3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(WaterUnitField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(WaterUnitField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel17)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                                        .addComponent(ElectricityUnitField3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel23)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ElectricityUnitField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(ElectricityUnitField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(38, 38, 38)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel28)
                                                    .addComponent(jLabel29)
                                                    .addComponent(jLabel30)
                                                    .addComponent(jLabel31)
                                                    .addComponent(jLabel32)
                                                    .addComponent(jLabel33))
                                                .addGap(48, 48, 48)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(MoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(33, 33, 33)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(WaterPriceField4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel13)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ElectricityPriceField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(WiFiPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(WaterUnitField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(DormitoryPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ElectricityUnitField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ElectricityPriceField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ElectricityPriceField3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ElectricityPriceField4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(WaterPriceField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(WaterPriceField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(WaterPriceField3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(50, 50, 50)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel21)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel27)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel22)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel2))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RoomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(415, 415, 415)
                                .addComponent(jLabel15)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DormitoryPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElectricityUnitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WaterUnitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WiFiPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElectricityPriceField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(ElectricityUnitField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElectricityPriceField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(ElectricityUnitField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ElectricityPriceField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(ElectricityUnitField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(ElectricityPriceField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(WaterPriceField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(WaterPriceField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(WaterUnitField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(WaterPriceField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(WaterUnitField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaterUnitField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(WaterPriceField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(MoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MoreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoreFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            roomNumber = RoomNumberField.getText();
            dormitoryPrice = Double.parseDouble(DormitoryPriceField.getText());
            electricityUnit = Double.parseDouble(ElectricityUnitField.getText());
            waterUnit = Double.parseDouble(WaterUnitField.getText());
            wiFiPrice = Double.parseDouble(WiFiPriceField.getText());
        } catch (Exception ex) {
            JOptionPane optionPane = new JOptionPane( );
            optionPane.setMessageType ( JOptionPane.ERROR_MESSAGE );
            optionPane.setMessage ( "Please Insert Number Only" );
            JDialog dialog = optionPane.createDialog ( null, "Error" );
            dialog.setVisible ( true );
            System.exit(0);
        }
        electricityPrice = ElectricityPrice.electricityPrice(electricityUnit);
        waterPrice = WaterPrice.waterPrice(waterUnit);
        total = Total.total(dormitoryPrice ,electricityPrice[3] ,waterPrice[3] ,wiFiPrice);

        RoomNumberField.setEditable(false);
        DormitoryPriceField.setEditable(false);
        ElectricityUnitField.setEditable(false);
        WaterUnitField.setEditable(false);
        WiFiPriceField.setEditable(false);
        ElectricityPriceField1.setText(String.valueOf(electricityPrice[0]));
        ElectricityPriceField2.setText(String.valueOf(electricityPrice[1]));
        ElectricityPriceField3.setText(String.valueOf(electricityPrice[2]));
        ElectricityPriceField4.setText(String.valueOf(electricityPrice[3]));
        WaterPriceField1.setText(String.valueOf(waterPrice[0]));
        WaterPriceField2.setText(String.valueOf(waterPrice[1]));
        WaterPriceField3.setText(String.valueOf(waterPrice[2]));
        WaterPriceField4.setText(String.valueOf(waterPrice[3]));
        ElectricityUnitField1.setText(String.valueOf(electricityPrice[0]/8));
        ElectricityUnitField2.setText(String.valueOf(electricityPrice[1]/9));
        ElectricityUnitField3.setText(String.valueOf(electricityPrice[2]/10));
        WaterUnitField1.setText(String.valueOf(waterPrice[0]/15));
        WaterUnitField2.setText(String.valueOf(waterPrice[1]/20));
        WaterUnitField3.setText(String.valueOf(waterPrice[2]/25));
        TotalField.setText(String.valueOf(total));
        DormitoryPriceField.setText(String.valueOf(dormitoryPrice));
        ElectricityUnitField.setText(String.valueOf(electricityUnit));
        WaterUnitField.setText(String.valueOf(waterUnit));
        WiFiPriceField.setText(String.valueOf(wiFiPrice));
        RoomNumberField.setText(roomNumber);
        MoreField.setVisible(true);
        jButton1.setVisible(false);
        jButton2.setVisible(true);
        jLabel34.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        more = MoreField.getText();
        if (more.equals("9")){
            jButton1.setVisible(true);
            MoreField.setVisible(false);
            jButton2.setVisible(false);
            jLabel34.setVisible(false);
            RoomNumberField.setEditable(true);
            DormitoryPriceField.setEditable(true);
            ElectricityUnitField.setEditable(true);
            WaterUnitField.setEditable(true);
            WiFiPriceField.setEditable(true);
            roomNumber = "" ;
            dormitoryPrice = 0;
            electricityUnit = 0;
            waterUnit = 0;
            wiFiPrice = 0;
            total = 0;
            for (int i = 0; i<4 ; i++){
                waterPrice[i] = 0;
                electricityPrice[i] = 0;
            }

            ElectricityPriceField1.setText("0");
            ElectricityPriceField2.setText("0");
            ElectricityPriceField3.setText("0");
            ElectricityPriceField4.setText("0");
            WaterPriceField1.setText("0");
            WaterPriceField2.setText("0");
            WaterPriceField3.setText("0");
            WaterPriceField4.setText("0");
            ElectricityUnitField1.setText("0");
            ElectricityUnitField2.setText("0");
            ElectricityUnitField3.setText("0");;
            WaterUnitField1.setText("0");
            WaterUnitField2.setText("0");
            WaterUnitField3.setText("0");
            TotalField.setText("0");
            DormitoryPriceField.setText("0");
            ElectricityUnitField.setText("0");
            WaterUnitField.setText("0");
            WiFiPriceField.setText("0");
            RoomNumberField.setText("");
        }
        else {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void WiFiPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WiFiPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WiFiPriceFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentDormitory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentDormitory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentDormitory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentDormitory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentDormitory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DormitoryPriceField;
    private javax.swing.JTextField ElectricityPriceField1;
    private javax.swing.JTextField ElectricityPriceField2;
    private javax.swing.JTextField ElectricityPriceField3;
    private javax.swing.JTextField ElectricityPriceField4;
    private javax.swing.JTextField ElectricityUnitField;
    private javax.swing.JTextField ElectricityUnitField1;
    private javax.swing.JTextField ElectricityUnitField2;
    private javax.swing.JTextField ElectricityUnitField3;
    private javax.swing.JTextField MoreField;
    private javax.swing.JTextField RoomNumberField;
    private javax.swing.JTextField TotalField;
    private javax.swing.JTextField WaterPriceField1;
    private javax.swing.JTextField WaterPriceField2;
    private javax.swing.JTextField WaterPriceField3;
    private javax.swing.JTextField WaterPriceField4;
    private javax.swing.JTextField WaterUnitField;
    private javax.swing.JTextField WaterUnitField1;
    private javax.swing.JTextField WaterUnitField2;
    private javax.swing.JTextField WaterUnitField3;
    private javax.swing.JTextField WiFiPriceField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
